# Generated by Django 5.1.3 on 2024-11-14 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoGlavnoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Содержание')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('link_to_photo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Предлагаемая услуга',
                'verbose_name_plural': 'Предлагаемые услуги',
            },
        ),
        migrations.CreateModel(
            name='Foundations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('link_to_photo', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Описание')),
                ('service_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.servicesoffered', verbose_name='Предлагаемая услуга')),
            ],
            options={
                'verbose_name': 'Фундамент',
                'verbose_name_plural': 'Фундаменты',
            },
        ),
    ]
