# Generated by Django 5.1.3 on 2024-11-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_infoglavnoe_servicesoffered_foundations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundations',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
