# Generated by Django 5.1.3 on 2024-11-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_foundations_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundations',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
