# Generated by Django 5.1.3 on 2024-11-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_foundations_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAtOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('date_of_meeting', models.DateField(verbose_name='Дата встречи')),
                ('meeting_time', models.TimeField(verbose_name='Время встречи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('privacy_policy_consent', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Клиент записан на дату и время:',
                'verbose_name_plural': 'Назначенные встречи',
                'ordering': ['date_of_meeting', 'meeting_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Контакты для обзвона'},
        ),
        migrations.AlterModelOptions(
            name='infoglavnoe',
            options={'verbose_name_plural': 'Информация на Главной странице'},
        ),
    ]
