# Generated by Django 5.1.3 on 2024-11-15 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_meetingatoffice_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingatoffice',
            name='date_of_meeting',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{2}.\\d{2}.\\d{4}$')], verbose_name='Дата встречи'),
        ),
    ]
